apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpmnserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpmnserver
  template:
    metadata:
      labels:
        app: bpmnserver
    spec:
      containers:
        - name: bpmnserver
          image: bpmnserver:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5432/ttqt_acb_sit_phase6
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres